### ISSUE TITLE
Problem in running the sample code in the python

### ISSUE THREAD

**Issue by Aminnzh2020** [rsiemens/ouster-python#4]
Hello
Thank you for providing the library for the ouster lidar.
I have a problem when I run the sample code:

from os1 import OS1
from os1.utils import xyz_points
def handler(raw_packet):
    """Takes each packet and log it to a file as xyz points"""
    with open('points.csv', 'a') as f:
        x, y, z = xyz_points(raw_packet)
        for coords in zip(x, y, z):
            f.write("{}\n".format(','.join(coords)))
os1 = OS1('10.5.5.87', '10.5.5.60', mode='1024x10')  # OS1 sensor IP, destination IP, and resolution
os1.start()
os1.run_forever(handler)

I appreciate it if you help me with the following problem and tell me what should I do to fix this error.
I set the lidar static IP address as 10.5.5.87 and the PC as 10.5.5.60, the lidar has ping and I can see the data in ouster studio software but, when I run the sample code the bellow error is happening :
Could you please let me know how I can fix it?

Exception happened during processing of request from ('10.5.5.87', 33179)
Traceback (most recent call last):
  File "C:\Users\royak\Programs\Python\Python36\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\royak\Programs\Python\Python36\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\royak\Programs\Python\Python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\royak\Programs\Python\Python36\lib\site-packages\os1\server.py", line 12, in __init__
    super(RequestHandler, self).__init__(*args, **kwargs)
  File "C:\Users\royak\Programs\Python\Python36\lib\socketserver.py", line 721, in __init__
    self.handle()
  File "C:\Users\royak\Programs\Python\Python36\lib\site-packages\os1\server.py", line 17, in handle
    self.handler(data)
  File "c:/Users/royak/OneDrive/Documents/imageprocessing/GOOD_projects/Ouser_Lidar_IP/OusterTest.py", line 10, in handler
    f.write("{}\n".format(','.join(coords)))
TypeError: sequence item 0: expected str instance, float found

Many thanks

**Comment by rsiemens** [comment]
Hi, thanks for posting this issue. Looks like I left a small error in the quick start example.

You can fix it by changing this:

```python
f.write("{}\n".format(','.join(coords)))
```

to this:

```python
csv_coords = ','.join([str(c) for c in coords])
f.write("{}\n".format(csv_coords)
```

I'll update the README with that shortly.
